### ISSUE TITLE
missing latest docker images

### ISSUE THREAD

**Issue by mehc555** [mbhall88/psdm#4]
Hi,

I don't see that docker version on quay.io, and the latest seems to be 0.2.0. Am I looking at the right place?

Thank you

**Comment by mbhall88** [comment]
Thanks for bringing this to my attention @mehc555. quay.io seems to have had issues building the Dockerfile for that release. I've had to recreate the github trigger, but the downside is I can't rebuild the 0.3.0 tag (the rust version in the docker file was too old). I have now relaxed the rust version in the container and it should now default to the latest - I have managed to build the latest commit. You can use `quay.io/mbhall88/psdm:latest` (or even drop the latest part if you want). There hasn't been any changes to the code since v0.3.0.

Alternatively, the biocontainers image for v0.3.0 is available at `quay.io/biocontainers/psdm:0.3.0--h715e4b3_1`
